# prepare_figures.R
# Export all manuscript figures as 300-DPI TIFF for Agricultural Systems submission
# Run from the project root: Rscript 05-Scripts/prepare_figures.R
#
# Requires: magick (install.packages("magick"))
# Output:   03-Results/submission_ready/*.tif

library(magick)
library(tools)

results_dir  <- "03-Results"
output_dir   <- file.path(results_dir, "submission_ready")
dir.create(output_dir, showWarnings = FALSE)

# ── Figure mapping: file → final submission name ──────────────────────────────
figure_files <- list(
  # Main text figures
  "kuresel_dagilim_haritasi.png"      = "Figure_01_Country_Distribution.tif",
  "YSA_prototip.png"                  = "Figure_02_ANN_Architecture.tif",
  "YSA_Tahmin_Son.png"                = "Figure_03_Prediction_Scatter.tif",
  "shap_beeswarm.png"                 = "Figure_04_SHAP_Beeswarm.tif",
  # Figure 5 (PDP) is dynamically generated by R chunk — export via ggsave separately
  "projeksion_trend.png"              = "Figure_06_2030_Projection.tif",
  "gelir_grubu_projesi.png"           = "Figure_07_Income_Group_Floor.tif",
  "sdg_uyum_tablosu.png"             = "Figure_08_SDG_Linkages.tif",
  # Supplementary figures
  "Olden_Analizi.png"                 = "Supplementary_S1_Olden.tif",
  "granger_nedensellik.png"           = "Supplementary_S2_Granger.tif",
  "dh_nedensellik.png"               = "Supplementary_S3_DH_Causality.tif",
  "Residual_Plot.png"                 = "Supplementary_S4_Residuals.tif",
  "ekc_yapi_taban_karsilastirma.png"  = "Supplementary_S5_EKC_Comparison.tif",
  "tarihsel_faktor_matrisi.png"       = "Supplementary_S6_Transformation_Matrix.tif",
  "Senaryo_Analizi.png"               = "Supplementary_S7_Scenario_Analysis.tif"
)

cat("Converting figures to 300-DPI TIFF...\n\n")
cat(sprintf("%-50s %s\n", "Source", "Output"))
cat(strrep("-", 80), "\n")

for (src_name in names(figure_files)) {
  src_path <- file.path(results_dir, src_name)
  dst_name <- figure_files[[src_name]]
  dst_path <- file.path(output_dir, dst_name)

  if (!file.exists(src_path)) {
    cat(sprintf("%-50s  MISSING — skipped\n", src_name))
    next
  }

  tryCatch({
    img <- image_read(src_path)
    info <- image_info(img)

    # Determine current effective DPI (default to 72 if not set)
    current_dpi <- if (!is.na(info$density[1]) && info$density[1] > 0) info$density[1] else 72

    # Target: 300 DPI output; upscale if current is lower
    if (current_dpi < 300) {
      scale_factor <- 300 / current_dpi
      new_w <- round(info$width  * scale_factor)
      new_h <- round(info$height * scale_factor)
      img   <- image_resize(img, paste0(new_w, "x", new_h, "!"))
    }

    img <- image_set_format(img, "TIFF")
    img <- image_write(img, path = dst_path, format = "tiff",
                       density = "300x300", depth = 8,
                       compression = "LZW")

    out_info <- image_info(image_read(dst_path))
    cat(sprintf("%-50s  %dx%d @ 300 DPI ✅\n",
                src_name, out_info$width, out_info$height))
  }, error = function(e) {
    cat(sprintf("%-50s  ERROR: %s\n", src_name, conditionMessage(e)))
  })
}

cat("\n")
cat("────────────────────────────────────────────────────────────────────────\n")
cat("IMPORTANT: Figure 5 (PDP) is generated by R chunk 'pdp_equipment_labor'.\n")
cat("To export it as TIFF, add to the chunk:\n")
cat("  #| fig-format: tiff\n")
cat("  #| fig-dpi: 300\n")
cat("  #| fig-width: 7\n")
cat("  #| fig-height: 5\n")
cat("then run: quarto render 04-Manuscript/MGO_HBI_Tarim_Konya_v4_EN.qmd\n")
cat("The TIFF will appear in the quarto output directory.\n")
cat("────────────────────────────────────────────────────────────────────────\n")
cat(sprintf("\nDone. Output files in: %s\n", normalizePath(output_dir, mustWork = FALSE)))
